#!/bin/sh

: "${CLEANUP}:=0"

BUILDER="cobdh/builder:v0.3.0"
ROOT=$(pwd)

rm -r "${ROOT}/build"

CURRENT=$(git describe --tags)
TAG="cobdh/view:${CURRENT}pre"

NAME="tmp_cobdh_${CURRENT}"
docker rm $NAME

# build
# MINIMAL:1 => copy minimal test data set
# MINIMAL:0 => do not copy any test data
docker run -it\
    -v "${ROOT}/../../":/var/src \
    -e VERSION="$CURRENT" \
    -e MINIMAL=1\
    --name ${NAME}\
    ${BUILDER}

if [ $? -ne 0 ]
then
    echo "could not copy and build"
    exit 1
fi

docker cp ${NAME}:/var/dst/ ${ROOT}/build

echo "git:   ${CURRENT}"
echo "tag:   ${TAG}"

docker build -f DOCKERFILE -t ${TAG} .

if [ $? -ne 0 ]
then
    echo "could not build deployment"
    exit 1
fi

echo "docker run ${TAG}"
docker run --rm -it -p 8090:8080 ${TAG}

if [ $CLEANUP -eq 1 ]
then
    echo "remove"
    docker rmi ${TAG}
fi
